### PR TITLE
Pack setup

### LINKED ISSUE #13: Choose documentation theme
Or make one. I've chosen "classic" as a placeholder, but there are other cool ones.

### PR DESCRIPTION
**Pull request by cgbriggs99**
I've added a simple pack.mcmeta and a script to convert images into unihex for unihex fonts.

### CODE REVIEW

**Comment by cgbriggs99** [comment]
To use this converter, run the ``unihex.py`` module and provide it with an image file and a code point. Other options can be found by using ``unihex.py --help``.

**Comment by cgbriggs99** [comment]
This module also exposes functions which can be used in scripts.

**Comment by cgbriggs99** [comment]
Somewhere along the development path, I designed a theme that looks ok. If someone else wants to suggest a new theme, I'm open.

**Review by randufett — APPROVED** [review]
The documentation site is looking nicer

**Pull request merged**
